version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017" # Porta padrão do MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Usuário administrador
      MONGO_INITDB_ROOT_PASSWORD: example # Senha do administrador
    volumes:
      - mongodb_data:/data/db # Persistência de dados

volumes:
  mongodb_data:
    driver: local
